require_relative "../config/application"

top100 = [{:title => "The Shawshank Redemption", :year => "1994", :imdb_rating => "9.2", :genre => "", :status => "false"},
{:title => "The Godfather", :year => "1972", :imdb_rating => "9.2", :genre => "", :status => "false"},
{:title => "The Godfather: Part II", :year => "1974", :imdb_rating => "9.0", :genre => "", :status => "false"},
{:title => "The Dark Knight", :year => "2008", :imdb_rating => "8.9", :genre => "", :status => "false"},
{:title => "Pulp Fiction", :year => "1994", :imdb_rating => "8.9", :genre => "", :status => "false"},
{:title => "12 Angry Men", :year => "1957", :imdb_rating => "8.9", :genre => "", :status => "false"},
{:title => "Schindler's List", :year => "1993", :imdb_rating => "8.9", :genre => "", :status => "false"},
{:title => "The Good, the Bad and the Ugly", :year => "1966", :imdb_rating => "8.9", :genre => "", :status => "false"},
{:title => "The Lord of the Rings: The Return of the King", :year => "2003", :imdb_rating => "8.9", :genre => "", :status => "false"},
{:title => "Fight Club", :year => "1999", :imdb_rating => "8.8", :genre => "", :status => "false"},
{:title => "The Lord of the Rings: The Fellowship of the Ring", :year => "2001", :imdb_rating => "8.8", :genre => "", :status => "false"},
{:title => "Star Wars: Episode V - The Empire Strikes Back", :year => "1980", :imdb_rating => "8.7", :genre => "", :status => "false"},
{:title => "Forrest Gump", :year => "1994", :imdb_rating => "8.7", :genre => "", :status => "false"},
{:title => "Inception", :year => "2010", :imdb_rating => "8.7", :genre => "", :status => "false"},
{:title => "One Flew Over the Cuckoo's Nest", :year => "1975", :imdb_rating => "8.7", :genre => "", :status => "false"},
{:title => "The Lord of the Rings: The Two Towers", :year => "2002", :imdb_rating => "8.7", :genre => "", :status => "false"},
{:title => "Goodfellas", :year => "1990", :imdb_rating => "8.7", :genre => "", :status => "false"},
{:title => "The Matrix", :year => "1999", :imdb_rating => "8.7", :genre => "", :status => "false"},
{:title => "Star Wars: Episode IV - A New Hope", :year => "1977", :imdb_rating => "8.7", :genre => "", :status => "false"},
{:title => "Seven Samurai", :year => "1954", :imdb_rating => "8.7", :genre => "", :status => "false"},
{:title => "City of God", :year => "2002", :imdb_rating => "8.6", :genre => "", :status => "false"},
{:title => "Se7en", :year => "1995", :imdb_rating => "8.6", :genre => "", :status => "false"},
{:title => "The Silence of the Lambs", :year => "1991", :imdb_rating => "8.6", :genre => "", :status => "false"},
{:title => "The Usual Suspects", :year => "1995", :imdb_rating => "8.6", :genre => "", :status => "false"},
{:title => "It's a Wonderful Life", :year => "1946", :imdb_rating => "8.6", :genre => "", :status => "false"},
{:title => "Life Is Beautiful", :year => "1997", :imdb_rating => "8.6", :genre => "", :status => "false"},
{:title => "Léon: The Professional", :year => "1994", :imdb_rating => "8.6", :genre => "", :status => "false"},
{:title => "Once Upon a Time in the West", :year => "1968", :imdb_rating => "8.6", :genre => "", :status => "false"},
{:title => "Interstellar", :year => "2014", :imdb_rating => "8.6", :genre => "", :status => "false"},
{:title => "Casablanca", :year => "1942", :imdb_rating => "8.5", :genre => "", :status => "false"},
{:title => "Saving Private Ryan", :year => "1998", :imdb_rating => "8.5", :genre => "", :status => "false"},
{:title => "American History X", :year => "1998", :imdb_rating => "8.5", :genre => "", :status => "false"},
{:title => "Spirited Away", :year => "2001", :imdb_rating => "8.5", :genre => "", :status => "false"},
{:title => "Raiders of the Lost Ark", :year => "1981", :imdb_rating => "8.5", :genre => "", :status => "false"},
{:title => "City Lights", :year => "1931", :imdb_rating => "8.5", :genre => "", :status => "false"},
{:title => "Psycho", :year => "1960", :imdb_rating => "8.5", :genre => "", :status => "false"},
{:title => "Rear Window", :year => "1954", :imdb_rating => "8.5", :genre => "", :status => "false"},
{:title => "The Intouchables", :year => "2011", :imdb_rating => "8.5", :genre => "", :status => "false"},
{:title => "Modern Times", :year => "1936", :imdb_rating => "8.5", :genre => "", :status => "false"},
{:title => "Whiplash", :year => "2014", :imdb_rating => "8.5", :genre => "", :status => "false"},
{:title => "Terminator 2: Judgment Day", :year => "1991", :imdb_rating => "8.5", :genre => "", :status => "false"},
{:title => "The Green Mile", :year => "1999", :imdb_rating => "8.5", :genre => "", :status => "false"},
{:title => "The Pianist", :year => "2002", :imdb_rating => "8.5", :genre => "", :status => "false"},
{:title => "Memento", :year => "2000", :imdb_rating => "8.5", :genre => "", :status => "false"},
{:title => "The Departed", :year => "2006", :imdb_rating => "8.5", :genre => "", :status => "false"},
{:title => "Inside Out", :year => "2015", :imdb_rating => "8.5", :genre => "", :status => "false"},
{:title => "Gladiator", :year => "2000", :imdb_rating => "8.5", :genre => "", :status => "false"},
{:title => "Apocalypse Now", :year => "1979", :imdb_rating => "8.5", :genre => "", :status => "false"},
{:title => "Back to the Future", :year => "1985", :imdb_rating => "8.5", :genre => "", :status => "false"},
{:title => "Sunset Blvd.", :year => "1950", :imdb_rating => "8.5", :genre => "", :status => "false"},
{:title => "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb", :year => "1964", :imdb_rating => "8.5", :genre => "", :status => "false"},
{:title => "The Prestige", :year => "2006", :imdb_rating => "8.5", :genre => "", :status => "false"},
{:title => "Alien", :year => "1979", :imdb_rating => "8.5", :genre => "", :status => "false"},
{:title => "The Lion King", :year => "1994", :imdb_rating => "8.4", :genre => "", :status => "false"},
{:title => "The Lives of Others", :year => "2006", :imdb_rating => "8.4", :genre => "", :status => "false"},
{:title => "The Great Dictator", :year => "1940", :imdb_rating => "8.4", :genre => "", :status => "false"},
{:title => "Cinema Paradiso", :year => "1988", :imdb_rating => "8.4", :genre => "", :status => "false"},
{:title => "The Shining", :year => "1980", :imdb_rating => "8.4", :genre => "", :status => "false"},
{:title => "Django Unchained", :year => "2012", :imdb_rating => "8.4", :genre => "", :status => "false"},
{:title => "Paths of Glory", :year => "1957", :imdb_rating => "8.4", :genre => "", :status => "false"},
{:title => "The Dark Knight Rises", :year => "2012", :imdb_rating => "8.4", :genre => "", :status => "false"},
{:title => "WALL·E", :year => "2008", :imdb_rating => "8.4", :genre => "", :status => "false"},
{:title => "American Beauty", :year => "1999", :imdb_rating => "8.4", :genre => "", :status => "false"},
{:title => "Grave of the Fireflies", :year => "1988", :imdb_rating => "8.4", :genre => "", :status => "false"},
{:title => "Aliens", :year => "1986", :imdb_rating => "8.4", :genre => "", :status => "false"},
{:title => "Citizen Kane", :year => "1941", :imdb_rating => "8.4", :genre => "", :status => "false"},
{:title => "North by Northwest", :year => "1959", :imdb_rating => "8.4", :genre => "", :status => "false"},
{:title => "Vertigo", :year => "1958", :imdb_rating => "8.4", :genre => "", :status => "false"},
{:title => "Oldboy", :year => "2003", :imdb_rating => "8.4", :genre => "", :status => "false"},
{:title => "Princess Mononoke", :year => "1997", :imdb_rating => "8.4", :genre => "", :status => "false"},
{:title => "Das Boot", :year => "1981", :imdb_rating => "8.4", :genre => "", :status => "false"},
{:title => "M", :year => "1931", :imdb_rating => "8.4", :genre => "", :status => "false"},
{:title => "Star Wars: Episode VI - Return of the Jedi", :year => "1983", :imdb_rating => "8.4", :genre => "", :status => "false"},
{:title => "Amélie", :year => "2001", :imdb_rating => "8.4", :genre => "", :status => "false"},
{:title => "Once Upon a Time in America", :year => "1984", :imdb_rating => "8.4", :genre => "", :status => "false"},
{:title => "Toy Story 3", :year => "2010", :imdb_rating => "8.3", :genre => "", :status => "false"},
{:title => "Reservoir Dogs", :year => "1992", :imdb_rating => "8.3", :genre => "", :status => "false"},
{:title => "Mad Max: Fury Road", :year => "2015", :imdb_rating => "8.3", :genre => "", :status => "false"},
{:title => "Witness for the Prosecution", :year => "1957", :imdb_rating => "8.3", :genre => "", :status => "false"},
{:title => "Braveheart", :year => "1995", :imdb_rating => "8.3", :genre => "", :status => "false"},
{:title => "A Clockwork Orange", :year => "1971", :imdb_rating => "8.3", :genre => "", :status => "false"},
{:title => "Double Indemnity", :year => "1944", :imdb_rating => "8.3", :genre => "", :status => "false"},
{:title => "Taxi Driver", :year => "1976", :imdb_rating => "8.3", :genre => "", :status => "false"},
{:title => "Requiem for a Dream", :year => "2000", :imdb_rating => "8.3", :genre => "", :status => "false"},
{:title => "To Kill a Mockingbird", :year => "1962", :imdb_rating => "8.3", :genre => "", :status => "false"},
{:title => "Lawrence of Arabia", :year => "1962", :imdb_rating => "8.3", :genre => "", :status => "false"},
{:title => "Eternal Sunshine of the Spotless Mind", :year => "2004", :imdb_rating => "8.3", :genre => "", :status => "false"},
{:title => "Full Metal Jacket", :year => "1987", :imdb_rating => "8.3", :genre => "", :status => "false"},
{:title => "The Sting", :year => "1973", :imdb_rating => "8.3", :genre => "", :status => "false"},
{:title => "Bicycle Thieves", :year => "1948", :imdb_rating => "8.3", :genre => "", :status => "false"},
{:title => "Amadeus", :year => "1984", :imdb_rating => "8.3", :genre => "", :status => "false"},
{:title => "Singin' in the Rain", :year => "1952", :imdb_rating => "8.3", :genre => "", :status => "false"},
{:title => "Monty Python and the Holy Grail", :year => "1975", :imdb_rating => "8.3", :genre => "", :status => "false"},
{:title => "Snatch", :year => "2000", :imdb_rating => "8.3", :genre => "", :status => "false"},
{:title => "2001: A Space Odyssey", :year => "1968", :imdb_rating => "8.3", :genre => "", :status => "false"},
{:title => "For a Few Dollars More", :year => "1965", :imdb_rating => "8.3", :genre => "", :status => "false"},
{:title => "The Kid", :year => "1921", :imdb_rating => "8.3", :genre => "", :status => "false"},
{:title => "Rashomon", :year => "1950", :imdb_rating => "8.3", :genre => "", :status => "false"},
{:title => "All About Eve", :year => "1950", :imdb_rating => "8.3", :genre => "", :status => "false"},
{:title => "L.A. Confidential", :year => "1997", :imdb_rating => "8.3"}]

top100.each do |hash|
    Movie.create(hash)
  end
